-- APT
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('apt', 'apt_opd_new', 'opd_new', 0, 'OPD New Attendees', 'V1kJRs8CtW4', 'xqSBj2KUlas', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('apt', 'apt_opd_total', 'opd_total', 1, 'OPT Total Attendence', 'V1kJRs8CtW4', 'xb4g6Zf7fAT', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('apt', 'apt_emtct_expected', 'emtct_expected', 2, 'Expected eMTCT Mothers on Appointment', 'V1kJRs8CtW4', 'xVpHSWaIBEX', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('apt', 'apt_emtct_missed', 'emtct_missed', 3, 'eMTCT Missed Appointments', 'V1kJRs8CtW4', 'LYT11E96lC5', 'gGhClrV5odI');
-- ARV
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('arv', 'arv_hiv_screening_test_kits', 'hiv_screening_test_kits', 0, 'HIV screening test kits', 'V1kJRs8CtW4', 'kteQimFQJom', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('arv', 'arv_emtct', 'emtct', 1, 'ARVs (Fixed - DC eMTCT)' 'V1kJRs8CtW4',, 'xgSJLvdm2cQ', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('arv', 'arv_nevirapine', 'nevirapine', 2, 'Nevirapine Therapy', 'V1kJRs8CtW4', 'JPVp2yLEimL', 'gGhClrV5odI');
-- CASES
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_ma', 'ma', 0, 'Cases of Malaria', 'V1kJRs8CtW4', 'fclvwNhzu7d', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_dy', 'dy', 1, 'Cases of Dysentery', 'V1kJRs8CtW4', 'NoJfAIcxjSY', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_sa', 'sa', 2, 'Cases of Severe Acute Respiratory Infection', 'V1kJRs8CtW4', 'MHtpmIQEnyc', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_af', 'af', 3, 'Cases of Acute Flacid Paralysis', 'V1kJRs8CtW4', 'U7cokRIptxu', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_ae', 'ae', 4, 'Cases of Adverse Events Following Immunization', 'V1kJRs8CtW4', 'fTwT8uX9Uto', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_ab', 'ab', 5, 'Cases of Animal Bites', 'V1kJRs8CtW4', 'mdIPCPfqXaJ', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_mg', 'mg', 6, 'Cases of Bacterial Meningitis', 'V1kJRs8CtW4', 'JxUexqKeXtZ', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_ch', 'ch', 7, 'Cases of Cholera', 'V1kJRs8CtW4', 'FPsN2bDpRru', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_gw', 'gw', 8, 'Cases of Guinea Worm', 'V1kJRs8CtW4', 'hzGgkiOjfRs', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_me', 'me', 9, 'Cases of Measles', 'V1kJRs8CtW4', 'v8HuPNb03yq', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_nt', 'nt', 10, 'Cases of Neonatal Tetanus', 'V1kJRs8CtW4', 'euf2TqlswFp', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_vf', 'vf', 11, 'Cases of Other Viral Hemorrhagic Fevers', 'V1kJRs8CtW4', 'BMJMdxh1Loy', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_pl', 'pl', 12, 'Cases of Plague', 'V1kJRs8CtW4', 'peyFcHisgZB', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_tf', 'tf', 13, 'Cases of Typhoid Fever', 'V1kJRs8CtW4', 'IkI01xB7RIi', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_yf', 'yf', 14, 'Cases of Yellow Fever', 'V1kJRs8CtW4', 'OE8baEzA2Cq', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_tb', 'tb', 15, 'Presumptive Multi Drug Resistance (MDR) TB', 'V1kJRs8CtW4', 'yzdPKhvgeXq', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_id', 'id', 16, 'Cases of Other Emerging Infectious Diseases', 'ZZrhG7CYNjy', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('cases', 'cases_rb', 'rb', 17, 'Cases of Rabies', 'V1kJRs8CtW4', 'tTGAElxDIWg', 'gGhClrV5odI');
-- DEATHS
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_ma', 'ma', 0, 'Deaths from Malaria', 'V1kJRs8CtW4', 'YXIu5CW9LPR', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_dy', 'dy', 1, 'Deaths from Dysentery', 'V1kJRs8CtW4', 'JTc25LIvtQb', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_sa', 'sa', 2, 'Deaths from Severe Acute Respiratory Infection', 'V1kJRs8CtW4', 'qdZbdsCpIr7', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_af', 'af', 3, 'Deaths from Acute Flacid Paralysis', 'V1kJRs8CtW4', 'XzYd9m4XaKS', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_ae', 'ae', 4, 'Deaths from Adverse Events Following Immunization', 'V1kJRs8CtW4', 'k2dUb4N7D0D', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_ab', 'ab', 5, 'Deaths from Animal Bites', 'V1kJRs8CtW4', 'UKYPpKnSBK4', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_mg', 'mg', 6, 'Deaths from Bacterial Meningitis', 'V1kJRs8CtW4', 'r3xIBQaeLsT', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_ch', 'ch', 7, 'Deaths from Cholera', 'V1kJRs8CtW4', 'QP9yftzrkne', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_gw', 'gw', 8, 'Deaths from Guinea Worm', 'V1kJRs8CtW4', 'yvbPC5zDb3c', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_me', 'me', 9, 'Deaths from Measles', 'V1kJRs8CtW4', 'tjTnFJ1QdVz', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_nt', 'nt', 10, 'Deaths from Neonatal Tetanus', 'V1kJRs8CtW4', 'tIh9TQxGOJU', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_vf', 'vf', 11, 'Deaths from Other Viral Hemorrhagic Fevers', 'V1kJRs8CtW4', 'BX2PYPKm8F9', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_pl', 'pl', 12, 'Deaths from Plague', 'V1kJRs8CtW4', 'hBcX7S7xBcu', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_tf', 'tf', 13, 'Deaths from Typhoid Fever', 'V1kJRs8CtW4', 'OMxmmYvvLai', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_yf', 'yf', 14, 'Deaths from Yellow Fever', 'V1kJRs8CtW4', 'w3mO7SZdbb8', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_tb', 'tb', 15, 'Presumptive Multi Drug Resistance (MDR) TB', 'V1kJRs8CtW4', 'eEruojUV6Jh', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_md', 'md', 16, 'Maternal deaths', 'V1kJRs8CtW4', 'ck3jFjr8fOT', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_pd', 'pd', 17, 'Perinatal deaths', 'V1kJRs8CtW4', 'nG5hrCX3vyP', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_id', 'id', 18, 'Deaths from Other Emerging Infectious Diseases', 'V1kJRs8CtW4', 'qHSErXOlcf3', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('deaths', 'death_rb', 'rb', 19, 'Deaths from Rabies', 'V1kJRs8CtW4', 'Dy90lwS6c6x', 'gGhClrV5odI');
-- MAT
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('mat', 'mat_suspected_malaria', 'suspected_malaria', 0, 'Suspected Malaria (fever)', 'V1kJRs8CtW4', 'KPmTI3TGwZw', '3W3d2AqT4Aq');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('mat', 'mat_rdt_tesed', 'rdt_tested', 1, 'RDT tested cases', 'V1kJRs8CtW4', 'KPmTI3TGwZw', 'kcXY5cWAOsB');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('mat', 'mat_rdt_positive', 'rdt_positive', 2, 'RDT positive cases', 'V1kJRs8CtW4', 'KPmTI3TGwZw', 'PfdPCxOoiBj');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('mat', 'mat_microscopy_tested', 'microscopy_tested', 3, 'Microscopy tested cases', 'V1kJRs8CtW4', 'KPmTI3TGwZw', 't8Jv78lnSbU');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('mat', 'mat_microscopy_positive', 'microscopy_positive', 4, 'Microscopy positive cases', 'V1kJRs8CtW4', 'KPmTI3TGwZw', '3rYpFjLrrYa');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('mat', 'mat_not_tested_treated', 'not_tested_treated', 5, 'Not tested cases treated', 'V1kJRs8CtW4', 'ZgPtploqq0L', 'w16OBdsg4b7');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('mat', 'mat_rdt_neg_treated', 'rdt_neg_treated', 6, ' RDT negative cases treated', 'V1kJRs8CtW4', 'ZgPtploqq0L', 'NfJyyb1eBaw');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('mat', 'mat_rdt_pos_treated', 'rdt_pos_treated', 7, 'RDT positive cases treated', 'V1kJRs8CtW4', 'ZgPtploqq0L', 'QOWAmZ7jBno');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('mat', 'mat_microscopy_neg_treated', 'microscopy_neg_tested', 8, 'Microscopy negative cases treated', 'V1kJRs8CtW4', 'ZgPtploqq0L', 'TTwU8Bv4fKm');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('mat', 'mat_microscopy_pos_treated', 'microscopy_pos_treated', 9, 'Microscopy positive cases treated', 'V1kJRs8CtW4', 'ZgPtploqq0L', 'vp37EZVg3xG');
-- TRA
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('tra', 'tra_act_tablets', 'act_tablets', 0, 'ACT (Tablets)', 'V1kJRs8CtW4', 'Ju0Cann41Ul', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('tra', 'tra_ors', 'ors', 1, 'ORS (Scakets)', 'V1kJRs8CtW4', 'zmimiDOJwaf', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('tra', 'tra_measles_vaccine', 'measles_vaccine', 2, 'Measles Vaccine', 'V1kJRs8CtW4', 'DgeykDdSLzI', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('tra', 'tra_amoxcilline', 'amoxcilline', 3, 'Amoxcilline', 'V1kJRs8CtW4', 'tFrWdigZ4oo', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('tra', 'tra_depo_provera', 'depo_provera', 4, 'Depo - Provera', 'V1kJRs8CtW4', 'v6ACxYNPIvm', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('tra', 'tra_iv_artesunate', 'iv_artesunate', 5, 'IV artesunate', 'V1kJRs8CtW4', 'O2OrXuZo4hB', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('tra', 'tra_fansidar', 'fansidar', 6, 'Fansidar', 'V1kJRs8CtW4', 'fX6A6NO18pY', 'gGhClrV5odI');
INSERT INTO dhis2_mtrack_indicators_mapping(form, slug, cmd, form_order, description, dataset, dataelement, category_combo) VALUES('tra', 'tra_rdt_malaria', 'rdt_malaria', 7, 'Malaria RDTs', 'V1kJRs8CtW4', 'CzsKMvQDwMV', 'gGhClrV5odI');
