INSERT INTO reporter_groups (name) VALUES('Accountant');
INSERT INTO reporter_groups (name) VALUES('As. DHO - Environ');
INSERT INTO reporter_groups (name) VALUES('As. DHO - Maternal');
INSERT INTO reporter_groups (name) VALUES('Biostatistician');
INSERT INTO reporter_groups (name) VALUES('Cold Chain Technician');
INSERT INTO reporter_groups (name) VALUES('DHO');
INSERT INTO reporter_groups (name) VALUES('DHT');
INSERT INTO reporter_groups (name) VALUES('FHD');
INSERT INTO reporter_groups (name) VALUES('HC');
INSERT INTO reporter_groups (name) VALUES('HIV');
INSERT INTO reporter_groups (name) VALUES('Health Educator');
INSERT INTO reporter_groups (name) VALUES('Health Inspector');
INSERT INTO reporter_groups (name) VALUES('Incharge');
INSERT INTO reporter_groups (name) VALUES('MAP Trained');
INSERT INTO reporter_groups (name) VALUES('Nutrition');
INSERT INTO reporter_groups (name) VALUES('Other CVS Reporters');
INSERT INTO reporter_groups (name) VALUES('PVHT');
INSERT INTO reporter_groups (name) VALUES('Pharmacist');
INSERT INTO reporter_groups (name) VALUES('Records Assistant');
INSERT INTO reporter_groups (name) VALUES('Secretary');
INSERT INTO reporter_groups (name) VALUES('Surveillance');
INSERT INTO reporter_groups (name) VALUES('VHT');
